### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by btbytes** [CyberShadow/SlimD#2] opened 2015-08-15 14:25 UTC
On  Mac OS X 10.10.4, using rdmd build 20150810

```
$ rdmd --build-only slimbuild/slimbuild.d                                                                                                                                                        
slimbuild/ae/sys/file.d(273): Error: function ae.sys.file.atomic!(copy, "target/to/name/dst").atomic (const(char)[] _param_0, const(char)[] _param_1, Flag _param_2) is not callable using argument types (string, string)
```

**Comment by CyberShadow** [comment] 2015-08-15 14:26
This project is for Win32 only. The error is due to a WONTFIX regression in Phobos, you can fast-forward the ae submodule to a version with a workaround.

**Closed as completed** 2015-08-15 14:26 UTC

**Comment by btbytes** [comment] 2015-08-15 14:33
:) Thanks. 

I understood that as much after continuing to read the forum posts and closed the ticket.
